# Generated by Django 3.2.9 on 2023-03-01 06:52

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubAjedrez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('address', models.CharField(max_length=100, verbose_name='sede social')),
                ('play_place', models.CharField(max_length=100, verbose_name='lugar de juego')),
                ('population', models.CharField(blank=True, max_length=100, verbose_name='población')),
                ('zip_code', models.CharField(blank=True, max_length=10, verbose_name='Código Postal')),
                ('president', models.CharField(max_length=100, verbose_name='presidente/a')),
                ('website', models.CharField(blank=True, max_length=100, verbose_name='sitio web')),
                ('social_network', models.CharField(blank=True, max_length=100, verbose_name='red social')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='teléfono')),
                ('contact', models.EmailField(max_length=100, verbose_name='contacto')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='contenido')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de publicación')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='fecha de edición')),
            ],
            options={
                'verbose_name_plural': 'clubes de ajedrez',
                'ordering': ['name'],
            },
        ),
    ]
