# Generated by Django 3.2.9 on 2023-03-01 06:52

import cloudinary_storage.storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Circular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título circular')),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('file_pdf', models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='pdf/%Y/%m/%d/', verbose_name='circulares')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de la circular')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='fecha de edición')),
                ('search_date', models.CharField(blank=True, max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_circulares', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
            ],
            options={
                'verbose_name_plural': 'circulares',
                'ordering': ['-publish'],
            },
        ),
    ]
