# Generated by Django 3.2.9 on 2023-03-01 06:52

import ckeditor_uploader.fields
import cloudinary_storage.storage
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TorneoDiputacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('file_pdf', models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='pdf/%Y/%m/%d/', verbose_name='bases')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='contenido')),
                ('image', models.ImageField(blank=True, upload_to='torneos', verbose_name='imagen')),
                ('quantity', models.PositiveIntegerField(verbose_name='aforo')),
                ('start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='inicio')),
                ('finish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='final')),
                ('end_registration', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fin de inscripción')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha de publicación')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='fecha de edición')),
                ('location', models.CharField(max_length=200, verbose_name='localidad')),
                ('province', models.CharField(max_length=200, verbose_name='provincia')),
                ('registre', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='registrarse')),
                ('inscribed', models.URLField(blank=True, verbose_name='inscritos')),
                ('has_category', models.BooleanField(default=False, verbose_name='hay categorías')),
            ],
            options={
                'verbose_name_plural': 'torneos diputación',
                'ordering': ['-start'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationTournamentDiputacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('surnames', models.CharField(max_length=100, verbose_name='apellidos')),
                ('mail', models.EmailField(max_length=100, verbose_name='correo electrónico')),
                ('population', models.CharField(max_length=100, verbose_name='población')),
                ('zip_code', models.CharField(max_length=10, verbose_name='Código Postal')),
                ('date_birth', models.DateTimeField(verbose_name='fecha de nacimiento')),
                ('phone', models.CharField(max_length=15, verbose_name='teléfono')),
                ('status', models.CharField(max_length=100, verbose_name='estado')),
                ('category', models.CharField(default='Ninguna', max_length=100, verbose_name='categoría')),
                ('privacy_policy', models.BooleanField(default=False, verbose_name='Aceptar política privacidad')),
                ('tournament_title', models.CharField(max_length=200, verbose_name='nombre del torneo')),
                ('paid', models.BooleanField(default=False, verbose_name='pagado')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='circuitos.torneodiputacion', verbose_name='torneo')),
            ],
            options={
                'verbose_name_plural': 'registros',
                'ordering': ['-surnames'],
            },
        ),
        migrations.AddConstraint(
            model_name='registrationtournamentdiputacion',
            constraint=models.UniqueConstraint(fields=('name', 'surnames', 'date_birth', 'tournament_title'), name='unique_registrationtournamentdiputacion'),
        ),
    ]
